name: Checkmarx OSA Scan
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.3
      with:
        cxAction: OsaScan
        cxServer: ${{ secrets.CX_OSA_SERVER }}
        cxUsername: ${{ secrets.CX_OSA_USERNAME }}
        cxPassword: ${{ secrets.CX_OSA_PASSWORD }}
        cxTeam: ${{ secrets.CX_OSA_TEAM }}
        cxExecutePackageDependency: true
        cxVersion: "2020.2.18"
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log